Está ocorrendo um erro com o banco de dados. O Baile não está sendo capaz de criar novas linhas para as princesas fairy tale para o próximo baile. O erro é


   File "main.py", line 28, in <module>
    universe.level.update_all()
  File "/home/nelson/glamour/stage.py", line 119, in update_all
    self.ball = self.ball or ball.Ball(self, self.universe, self.princesses[0])
  File "/home/nelson/glamour/ball.py", line 21, in __init__
    self.Frame      = BallFrame(self)
  File "/home/nelson/glamour/ball.py", line 111, in __init__
    self.set_next_ball_clothes()
  File "/home/nelson/glamour/ball.py", line 133, in set_next_ball_clothes
    cursor.execute("INSERT INTO "+p+" VALUES ("+str(row['id']+1)+" , "+str(row["hair_back"])+" , '"+row["skin"]+"', '"+random.choice(faces)+"' , '"+row['hair']+"' , '"+random.choice(shoes)+"' , '"+dresses[dress_no]+"', '"+row['arm']+"', "+arm_dresses[dress_no]+", '"+random.choice(accessories)+"')")
TypeError: coercing to Unicode: need string or buffer, int found
nelson@Marvim:~/glamour$ 


A questão é tratada no arquivo save, no arquivo db e no arquivo ball
